export const COUNTRY_LIST = [
  { name: "Afganistán", code: "af", dialCode: "+93" },
  { name: "Albania", code: "al", dialCode: "+355" },
  { name: "Alemania", code: "de", dialCode: "+49" },
  { name: "Andorra", code: "ad", dialCode: "+376" },
  { name: "Angola", code: "ao", dialCode: "+244" },
  { name: "Antigua y Barbuda", code: "ag", dialCode: "+1" },
  { name: "Arabia Saudita", code: "sa", dialCode: "+966" },
  { name: "Argelia", code: "dz", dialCode: "+213" },
  { name: "Argentina", code: "ar", dialCode: "+54" },
  { name: "Armenia", code: "am", dialCode: "+374" },
  { name: "Australia", code: "au", dialCode: "+61" },
  { name: "Austria", code: "at", dialCode: "+43" },
  { name: "Azerbaiyán", code: "az", dialCode: "+994" },
  { name: "Bahamas", code: "bs", dialCode: "+1" },
  { name: "Bangladés", code: "bd", dialCode: "+880" },
  { name: "Barbados", code: "bb", dialCode: "+1" },
  { name: "Baréin", code: "bh", dialCode: "+973" },
  { name: "Bélgica", code: "be", dialCode: "+32" },
  { name: "Belice", code: "bz", dialCode: "+501" },
  { name: "Benín", code: "bj", dialCode: "+229" },
  { name: "Bielorrusia", code: "by", dialCode: "+375" },
  { name: "Birmania", code: "mm", dialCode: "+95" },
  { name: "Bolivia", code: "bo", dialCode: "+591" },
  { name: "Bosnia y Herzegovina", code: "ba", dialCode: "+387" },
  { name: "Botsuana", code: "bw", dialCode: "+267" },
  { name: "Brasil", code: "br", dialCode: "+55" },
  { name: "Brunéi", code: "bn", dialCode: "+673" },
  { name: "Bulgaria", code: "bg", dialCode: "+359" },
  { name: "Burkina Faso", code: "bf", dialCode: "+226" },
  { name: "Burundi", code: "bi", dialCode: "+257" },
  { name: "Bután", code: "bt", dialCode: "+975" },
  { name: "Cabo Verde", code: "cv", dialCode: "+238" },
  { name: "Camboya", code: "kh", dialCode: "+855" },
  { name: "Camerún", code: "cm", dialCode: "+237" },
  { name: "Canadá", code: "ca", dialCode: "+1" },
  { name: "Catar", code: "qa", dialCode: "+974" },
  { name: "Chad", code: "td", dialCode: "+235" },
  { name: "Chile", code: "cl", dialCode: "+56" },
  { name: "China", code: "cn", dialCode: "+86" },
  { name: "Chipre", code: "cy", dialCode: "+357" },
  { name: "Ciudad del Vaticano", code: "va", dialCode: "+39" },
  { name: "Colombia", code: "co", dialCode: "+57" },
  { name: "Comoras", code: "km", dialCode: "+269" },
  { name: "Corea del Norte", code: "kp", dialCode: "+850" },
  { name: "Corea del Sur", code: "kr", dialCode: "+82" },
  { name: "Costa de Marfil", code: "ci", dialCode: "+225" },
  { name: "Costa Rica", code: "cr", dialCode: "+506" },
  { name: "Croacia", code: "hr", dialCode: "+385" },
  { name: "Cuba", code: "cu", dialCode: "+53" },
  { name: "Dinamarca", code: "dk", dialCode: "+45" },
  { name: "Dominica", code: "dm", dialCode: "+1" },
  { name: "Ecuador", code: "ec", dialCode: "+593" },
  { name: "Egipto", code: "eg", dialCode: "+20" },
  { name: "El Salvador", code: "sv", dialCode: "+503" },
  { name: "Emiratos Árabes Unidos", code: "ae", dialCode: "+971" },
  { name: "Eritrea", code: "er", dialCode: "+291" },
  { name: "Eslovaquia", code: "sk", dialCode: "+421" },
  { name: "Eslovenia", code: "si", dialCode: "+386" },
  { name: "España", code: "es", dialCode: "+34" },
  { name: "Estados Unidos", code: "us", dialCode: "+1" },
  { name: "Estonia", code: "ee", dialCode: "+372" },
  { name: "Etiopía", code: "et", dialCode: "+251" },
  { name: "Filipinas", code: "ph", dialCode: "+63" },
  { name: "Finlandia", code: "fi", dialCode: "+358" },
  { name: "Fiyi", code: "fj", dialCode: "+679" },
  { name: "Francia", code: "fr", dialCode: "+33" },
  { name: "Gabón", code: "ga", dialCode: "+241" },
  { name: "Gambia", code: "gm", dialCode: "+220" },
  { name: "Georgia", code: "ge", dialCode: "+995" },
  { name: "Ghana", code: "gh", dialCode: "+233" },
  { name: "Granada", code: "gd", dialCode: "+1" },
  { name: "Grecia", code: "gr", dialCode: "+30" },
  { name: "Guatemala", code: "gt", dialCode: "+502" },
  { name: "Guinea", code: "gn", dialCode: "+224" },
  { name: "Guinea Ecuatorial", code: "gq", dialCode: "+240" },
  { name: "Guinea-Bisáu", code: "gw", dialCode: "+245" },
  { name: "Guyana", code: "gy", dialCode: "+592" },
  { name: "Haití", code: "ht", dialCode: "+509" },
  { name: "Honduras", code: "hn", dialCode: "+504" },
  { name: "Hungría", code: "hu", dialCode: "+36" },
  { name: "India", code: "in", dialCode: "+91" },
  { name: "Indonesia", code: "id", dialCode: "+62" },
  { name: "Irak", code: "iq", dialCode: "+964" },
  { name: "Irán", code: "ir", dialCode: "+98" },
  { name: "Irlanda", code: "ie", dialCode: "+353" },
  { name: "Islandia", code: "is", dialCode: "+354" },
  { name: "Islas Marshall", code: "mh", dialCode: "+692" },
  { name: "Islas Salomón", code: "sb", dialCode: "+677" },
  { name: "Israel", code: "il", dialCode: "+972" },
  { name: "Italia", code: "it", dialCode: "+39" },
  { name: "Jamaica", code: "jm", dialCode: "+1" },
  { name: "Japón", code: "jp", dialCode: "+81" },
  { name: "Jordania", code: "jo", dialCode: "+962" },
  { name: "Kazajistán", code: "kz", dialCode: "+7" },
  { name: "Kenia", code: "ke", dialCode: "+254" },
  { name: "Kirguistán", code: "kg", dialCode: "+996" },
  { name: "Kiribati", code: "ki", dialCode: "+686" },
  { name: "Kuwait", code: "kw", dialCode: "+965" },
  { name: "Laos", code: "la", dialCode: "+856" },
  { name: "Lesoto", code: "ls", dialCode: "+266" },
  { name: "Letonia", code: "lv", dialCode: "+371" },
  { name: "Líbano", code: "lb", dialCode: "+961" },
  { name: "Liberia", code: "lr", dialCode: "+231" },
  { name: "Libia", code: "ly", dialCode: "+218" },
  { name: "Liechtenstein", code: "li", dialCode: "+423" },
  { name: "Lituania", code: "lt", dialCode: "+370" },
  { name: "Luxemburgo", code: "lu", dialCode: "+352" },
  { name: "Madagascar", code: "mg", dialCode: "+261" },
  { name: "Malasia", code: "my", dialCode: "+60" },
  { name: "Malaui", code: "mw", dialCode: "+265" },
  { name: "Maldivas", code: "mv", dialCode: "+960" },
  { name: "Malí", code: "ml", dialCode: "+223" },
  { name: "Malta", code: "mt", dialCode: "+356" },
  { name: "Marruecos", code: "ma", dialCode: "+212" },
  { name: "Mauricio", code: "mu", dialCode: "+230" },
  { name: "Mauritania", code: "mr", dialCode: "+222" },
  { name: "México", code: "mx", dialCode: "+52" },
  { name: "Micronesia", code: "fm", dialCode: "+691" },
  { name: "Moldavia", code: "md", dialCode: "+373" },
  { name: "Mónaco", code: "mc", dialCode: "+377" },
  { name: "Mongolia", code: "mn", dialCode: "+976" },
  { name: "Montenegro", code: "me", dialCode: "+382" },
  { name: "Mozambique", code: "mz", dialCode: "+258" },
  { name: "Namibia", code: "na", dialCode: "+264" },
  { name: "Nauru", code: "nr", dialCode: "+674" },
  { name: "Nepal", code: "np", dialCode: "+977" },
  { name: "Nicaragua", code: "ni", dialCode: "+505" },
  { name: "Níger", code: "ne", dialCode: "+227" },
  { name: "Nigeria", code: "ng", dialCode: "+234" },
  { name: "Noruega", code: "no", dialCode: "+47" },
  { name: "Nueva Zelanda", code: "nz", dialCode: "+64" },
  { name: "Omán", code: "om", dialCode: "+968" },
  { name: "Países Bajos", code: "nl", dialCode: "+31" },
  { name: "Pakistán", code: "pk", dialCode: "+92" },
  { name: "Palaos", code: "pw", dialCode: "+680" },
  { name: "Panamá", code: "pa", dialCode: "+507" },
  { name: "Papúa Nueva Guinea", code: "pg", dialCode: "+675" },
  { name: "Paraguay", code: "py", dialCode: "+595" },
  { name: "Perú", code: "pe", dialCode: "+51" },
  { name: "Polonia", code: "pl", dialCode: "+48" },
  { name: "Portugal", code: "pt", dialCode: "+351" },
  { name: "Reino Unido", code: "gb", dialCode: "+44" },
  { name: "República Centroafricana", code: "cf", dialCode: "+236" },
  { name: "República Checa", code: "cz", dialCode: "+420" },
  { name: "República de Macedonia", code: "mk", dialCode: "+389" },
  { name: "República del Congo", code: "cg", dialCode: "+242" },
  { name: "República Democrática del Congo", code: "cd", dialCode: "+243" },
  { name: "República Dominicana", code: "do", dialCode: "+1" },
  { name: "Ruanda", code: "rw", dialCode: "+250" },
  { name: "Rumanía", code: "ro", dialCode: "+40" },
  { name: "Rusia", code: "ru", dialCode: "+7" },
  { name: "Samoa", code: "ws", dialCode: "+685" },
  { name: "San Cristóbal y Nieves", code: "kn", dialCode: "+1" },
  { name: "San Marino", code: "sm", dialCode: "+378" },
  { name: "San Vicente y las Granadinas", code: "vc", dialCode: "+1" },
  { name: "Santa Lucía", code: "lc", dialCode: "+1" },
  { name: "Santo Tomé y Príncipe", code: "st", dialCode: "+239" },
  { name: "Senegal", code: "sn", dialCode: "+221" },
  { name: "Serbia", code: "rs", dialCode: "+381" },
  { name: "Seychelles", code: "sc", dialCode: "+248" },
  { name: "Sierra Leona", code: "sl", dialCode: "+232" },
  { name: "Singapur", code: "sg", dialCode: "+65" },
  { name: "Siria", code: "sy", dialCode: "+963" },
  { name: "Somalia", code: "so", dialCode: "+252" },
  { name: "Sri Lanka", code: "lk", dialCode: "+94" },
  { name: "Suazilandia", code: "sz", dialCode: "+268" },
  { name: "Sudáfrica", code: "za", dialCode: "+27" },
  { name: "Sudán", code: "sd", dialCode: "+249" },
  { name: "Sudán del Sur", code: "ss", dialCode: "+211" },
  { name: "Suecia", code: "se", dialCode: "+46" },
  { name: "Suiza", code: "ch", dialCode: "+41" },
  { name: "Surinam", code: "sr", dialCode: "+597" },
  { name: "Tailandia", code: "th", dialCode: "+66" },
  { name: "Tanzania", code: "tz", dialCode: "+255" },
  { name: "Tayikistán", code: "tj", dialCode: "+992" },
  { name: "Timor Oriental", code: "tl", dialCode: "+670" },
  { name: "Togo", code: "tg", dialCode: "+228" },
  { name: "Tonga", code: "to", dialCode: "+676" },
  { name: "Trinidad y Tobago", code: "tt", dialCode: "+1" },
  { name: "Túnez", code: "tn", dialCode: "+216" },
  { name: "Turkmenistán", code: "tm", dialCode: "+993" },
  { name: "Turquía", code: "tr", dialCode: "+90" },
  { name: "Tuvalu", code: "tv", dialCode: "+688" },
  { name: "Ucrania", code: "ua", dialCode: "+380" },
  { name: "Uganda", code: "ug", dialCode: "+256" },
  { name: "Uruguay", code: "uy", dialCode: "+598" },
  { name: "Uzbekistán", code: "uz", dialCode: "+998" },
  { name: "Vanuatu", code: "vu", dialCode: "+678" },
  { name: "Venezuela", code: "ve", dialCode: "+58" },
  { name: "Vietnam", code: "vn", dialCode: "+84" },
  { name: "Yemen", code: "ye", dialCode: "+967" },
  { name: "Yibuti", code: "dj", dialCode: "+253" },
  { name: "Zambia", code: "zm", dialCode: "+260" },
  { name: "Zimbabue", code: "zw", dialCode: "+263" }
];
